//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public int EmployeeId { get; set; }
        public string FullNameId { get; set; }
        public string AddressId { get; set; }
        public string PhoneNumberId { get; set; }
        public string Position { get; set; }
    }
}
